#!/bin/bash
#SBATCH --job-name=craftax-voyage
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=00:30:00
#SBATCH --output=/home/oasik/craftax-voyage/logs/%j.out
#SBATCH --error=/home/oasik/craftax-voyage/logs/%j.err

cd ~oasik/craftax-voyage/

rm -rf .venv

uv python install 3.12 

uv venv --python 3.12 --managed-python
source .venv/bin/activate

uv pip install -e Craftax-1.6.1[dev]
uv pip install vllm

#vllm serve Qwen/Qwen3.5-9B > logs/${SLURM_JOB_ID}_vllm.log 2>&1 &
#vllm serve Qwen/Qwen3.5-9B --tensor-parallel-size 2 > logs/${SLURM_JOB_ID}_vllm.log 2>&1 &
vllm serve unsloth/Qwen3.5-9B-GGUF > logs/${SLURM_JOB_ID}_vllm.log 2>&1 &

VLLM_PID=$!

echo "Started vLLM with PID $VLLM_PID"
echo "Waiting for vLLM to become ready..."

until curl -s http://localhost:8000/v1/models > /dev/null; do
    if ! kill -0 "$VLLM_PID" 2>/dev/null; then
        echo "vLLM failed to start. Check logs/${SLURM_JOB_ID}_vllm.log"
        exit 1
    fi

    sleep 2
done

echo "vLLM is ready."

python generate_skills.py 
python generate_skills.py /home/oasik/craftax-voyage/generated_skills6
python generate_skills.py /home/oasik/craftax-voyage/generated_skills7
python generate_skills.py /home/oasik/craftax-voyage/generated_skills8
python generate_skills.py /home/oasik/craftax-voyage/generated_skills9

kill "$VLLM_PID"